##
# Memcached tasks
#
---
- name: Install daemon.
  apt: pkg={{ item }} state=latest
  with_items:
    - memcached
    - "{{ 'php5-memcache' if php_version == '5.5' else 'php-memcache' }}"
  notify: restart PHP server

- name: Configuring memcached.
  template: src=etc-memcached-conf.j2 dest=/etc/memcached.conf mode=644
  notify: restart memcached
